name: First Deploy
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Code 
      uses: actions/checkout@v3
    - name: Install Dependencies 
      run: npm ci
    - name: Test lint
      run: npm run lint
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Clone Code 
      uses: actions/checkout@v3
    - name: Install Dependencies 
      run: npm ci
    - name: Test lint
      run: npm run lint
    - name: Test code
      run: npm run test
    - name: Build 
      run: npm run build
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Clone Code 
      uses: actions/checkout@v3
    - name: Install Dependencies 
      run: npm ci
    - name: Test lint
      run: npm run lint
    - name: Test code
      run: npm run test
    - name: Build 
      run: npm run build
    - name: Deploy
      run: echo "Deployed"
